name: Publish NPM @arte-pt/accessmonitor-rulesets Package

on:
  push:
    branches:
      - main
    paths:
      - 'metadata-package/**'
  workflow_dispatch: 

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write  
      pull-requests: write 
      id-token: write  

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install
        working-directory: ./metadata-package
      - name: Debug Changeset Path
        working-directory: ./metadata-package
        run: |
          echo "Onde estou?" && pwd
          echo "O que vejo aqui dentro?"
          ls -la
          echo "Consigo ver a pasta .changeset?"
          ls -la .changeset/ || echo "Pasta .changeset não encontrada!"
      - name: Publish to NPM (Manual CLI)
        id: changesets
        working-directory: ./metadata-package 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Starting publishing."
          
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          npx changeset version
          
          npx changeset publish
